### ISSUE TITLE
Initialization of CMA-ES mean

### ISSUE THREAD

**Issue by Reiyan** [sjvrijn/ModEA#5]
Hi,

is the initialization of the mean of CMA-ES expected to be drawn from a standard distribution rather than a uniform one?
See Algorithms.py Line 475
`wcm = (np.random.randn(n, 1) * (u_bound - l_bound)) + l_bound`

The bounds will not be respected in this case, np.random.rand() might be the more appropriated function.

Kind regards,

Raphael

**Comment by sjvrijn** [comment]
Yes, the CMA-ES is supposed to be drawn from the normal distribution, but you are correct that this does not respect the bounds. Thanks for catching that @Reiyan.
